# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/flocky',
                'doc_host': 'https://CarloLepelaars.github.io',
                'git_url': 'https://github.com/CarloLepelaars/flocky',
                'lib_path': 'flocky'},
  'syms': {'flocky.api': {'flocky.api.get_task': ('api.html#get_task', 'flocky/api.py')}, 'flocky.core': {}, 'flocky.gpu': {}}}
