"""Interaction with Flock.io's API"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_api.ipynb.

# %% auto 0
__all__ = ['get_task']

# %% ../nbs/01_api.ipynb 2
import pandas as pd
from fastcore.all import *

from .core import BASE_URL

# %% ../nbs/01_api.ipynb 3
def get_task(task_id: int):
    return AttrDict(loads(urlread(f'{BASE_URL}tasks/get?task_id={task_id}')))
