"""Basic utilities"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['BASE_URL']

# %% ../nbs/00_core.ipynb 3
BASE_URL = 'https://fed-ledger-prod.flock.io/api/v1/'
BASE_URL
